{% set name = "cltoolbox" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cltoolbox-{{ version }}.tar.gz
  sha256: 180fb9095f58a4afc821ea9a4468dd4ed8e4a0a75fe00c923f05a40956e7f260

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - docstring_parser
    - docutils

test:
  imports:
    - cltoolbox
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/cltoolbox/
  summary: Python library for creating and manipulating CLIs
  license: BSD-3-Clause AND MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - timcera
