{% set name = "cltoolbox" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cltoolbox-{{ version }}.tar.gz
  sha256: e6f675884afa0537b97f72e7b7c23864699b73873a1070243c0fc4f8c04f490f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - docstring_parser
    - docutils
    - python >=3.8

test:
  imports:
    - cltoolbox
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/cltoolbox/
  summary: Python library for creating and manipulating CLIs
  license: BSD-3-Clause AND MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - timcera
