{% set name = "cltoolbox" %}
{% set version = "4.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cltoolbox-{{ version }}.tar.gz
  sha256: 57ab81e975930cfa20d8c729de3f64b47213e7d21ef60b53f699ed6fc8f13116

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - docstring_parser
    - docutils

test:
  imports:
    - cltoolbox
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/cltoolbox/
  summary: Python library for creating and manipulating CLIs
  license: BSD-3-Clause AND MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - timcera
