{% set name = "cltoolbox" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cltoolbox-{{ version }}.tar.gz
  sha256: dc50e45b858b94302585c35ac6859c612a2ae82c479127dc62ec586626e70af5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - docstring_parser
    - docutils
    - python >=3.8

test:
  imports:
    - cltoolbox
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/cltoolbox/
  summary: Python library for creating and manipulating CLIs
  license: BSD-3-Clause AND MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - timcera
